[tools]
bun = "1.3.2"
node = "24.11.0"

[tasks.bootstrap]
description = "Initialize the workspace."
run = './tools/bootstrap.sh'
alias = "bs"

[tasks.clean]
description = "Clean this workspace."
run = [
    'bun run clean',
]

[tasks.doctor]
description = "Show information about the installed tooling."
run = './tools/doctor.sh'
alias = "dr"
